### PR TITLE
Create chapter_3.6.5_research_bug_tracker.md

### PR DESCRIPTION
**Pull request by mnallajerla**
### 3.6.5 research_bug_tracker

### CODE REVIEW

**Comment by lijenn** [comment]
@mnallajerla I think you created this chapter on the wrong repo since I see this pull request on the lzim/mtl repo for the MTL Manual (https://mtl.how/manual).

When we want this chapter/file to be on the lzim/teampsd repo for the Team PSD Manual (https://mtl.how/teampsd_manual).
You'll need to make the edits and create a pull request on the lzim/teampsd repo. 
Then we should close this pull request and your branch on this repo.

Let us know if you have any questions!

**Comment by staceypark** [comment]
@mnallajerla 
Great job creating your first pull request & bookdown manual edit. 

Some feedback:
- This pull request should be for the mtl.how/teampsd_manual which is situation in the lzim/teampsd repository.
- We want a section for both the research_bug_tracker and research_feature_tracker
- I think you misunderstood what I meant by "add a section". I meant for you to add the header & content in a format similar to how the other tracker sections are structured: brief description about the purpose of the tracker, followed by the tracker columns and their purpose.
image

Let me know if you have any other questions!

**Comment by mnallajerla** [comment]
@staceypark @lijenn I believe I made the edit correctly this time, in the right repo. Let me know what you think, or if I need to correct anything else. Thank you!

**Comment by lijenn** [comment]
Closing this as the work is now in https://github.com/lzim/teampsd/pull/2271

**Pull request closed without merging**
