### PR TITLE
Feature blue guides update

### PR DESCRIPTION
**Pull request by mnallajerla**
Hi jenn, sorry for the delay. Here are all the edits for Blue guides scoped from now through the end of the week of 4/11. 

For sessions 5-8, I recommend resizing the GIFs to be similar to the ones in Sessions 2-3. The smaller size also makes the guides look neater and more easy to read.

### CODE REVIEW

**Comment by lijenn** [comment]
Closing this branch for now since @lijenn will post Session 1, 2, 10 by Monday 4/18 as Lindsey and Jenn have edited the story map schedule for Story C. 

Afterwards, Jenn will help update/sync this branch with the latest updates.

**Comment by mnallajerla** [comment]
Hi @lijenn - 

These are all the edits I made for Sessions 5-8 prior to my leave, that have been ready for QA. I see your note about closing the branch without pulling in the edits. Would you please QA these edits and pull them into Master? Thanks so much!

**Comment by mnallajerla** [comment]
Hi @lijenn - I know you have a lot on your plate so please let me know if you would like to divvy this up differently. However, I think we are on scheduled to RECORD for these sessions next week, so we'd need the guides in PROD by then. Thank you!

**Comment by lijenn** [comment]
@mnallajerla I'm wrapping this up today :) Thanks for checking in!

**Pull request merged**
