### PR TITLE
wk2_jan: Update 7.0_mtl_technical_manual_facilitator.md

### PR DESCRIPTION
**Pull request by jamesmrollins**
- Added instructions and images for creating and downloading Team Data file from DataUI.
- Placed instructions immediately preceding the upload team data file instructions for Sim UI.
- Added instructions and images for reporting a bug from the Sim UI.
- Added instructions and images for reporting a bug directly into GitHub.

### CODE REVIEW

**Comment by epearman** [comment]
@jamesmrollins This looks great! thanks for adding these.

@emilymetcalf114 any feedback or additions before merging this?

**Comment by jamesmrollins** [comment]
> This looks amazing @jamesmrollins!!! Beautiful screen shots!
> 
> A couple of super quick updates to the language might add a little bit more clarity (added language in bold below:
> 
> Line 137: When a Team Data file is downloaded **from the Data UI**
> 
> Line 138: The facilitator will be able to assign the **Team Data file** to various teams **or worlds** of their choice
> 
> Line 350: 2. Describe the issue… **Do not include PII or other Site identifiable information. Instead use generic language such as “_MTL Blue live_ team on Mondays at 9am”**
> 
> Line 372: 4. Complete Issue Form. **Do not include PII or other Site identifiable information. Instead use generic language such as “_MTL Blue live_ team on Mondays at 9am”**

Hi @emilymetcalf114 - These requested changes are complete.

**Comment by jamesmrollins** [comment]
@emilymetcalf114 @epearman Are you familiar with the functions below?

1.  Click the "Review" button.
image

2. Enter general comments and click approved or comment without approval.

image

3.  If needed, enter line-by-line comments.

image

**Comment by emilymetcalf114** [comment]
Thanks @jamesmrollins , I didn't realize you could leave comments on individual line items, that's really helpful! 
It might be helpful to add these instructions and screenshots to the manual for future users!

**Comment by jamesmrollins** [comment]
Good idea!

**Pull request merged**
